### ISSUE TITLE
Need more details on how to install on Linux

### ISSUE THREAD

**Issue by aproposnix** [jasons-gh/the-chomsky-index#1]
I'm just following up from the Reddit thread. It would be nice if there were more information on how to run this properly on Linux. 

I was able to compile the program from source after installing QT5  (which was an undocumented requirement) but I have no idea how to actually use it as there doesn't seem to be a binary. 

Another option would be to make the Windows binary compatible with WINE (right now it crashes on start). 

I'm really looking forward to using this! Thanks so much for working on it.

**Comment by devins2518** [comment]
Not the maintainer, but if you're on Linux, do `git clone https://github.com/jasons-gh/the-chomsky-index.git` and cd into the folder. You then have two choices:
1) Install using a virtual env
- `pip3 install virtualenv`
- `virtualenv env`
- `source env/bin/activate`
- `pip3 install -r requirements.txt`
- `pip3 install sip`
- Then just run the pyinstaller command from the README
2) Just install on the system. 
- `pip3 install -r requirements.txt`
- `pip3 install sip`
- Run the pyinstaller command from the README

**Comment by jasons-gh** [comment]
@devins2518 Hey, have you successfully installed it on any platform, and if so which ones?

**Comment by devins2518** [comment]
I've been able to install on windows and linux. Linux does need a hidden import called `sip` that is probably needed for the qt package. It can be solved with a simple `pip3 install sip`, and then it should work fine. It appears in a folder called dist/display.

**Comment by jasons-gh** [comment]
I've updated the Linux instructions and should upload a single file release soon.

**Comment by aproposnix** [comment]
that works for me. Closing the issue as I see this as resolved. Thanks a lot! This is really a handy reference.
